apiVersion: apps/v1
kind: Deployment
metadata:
  name: xhdfsiah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xhdfsiah
  template:
    metadata:
      labels:
        app: xhdfsiah
    spec:
      containers:
      - image: okteto.dev/xhdfsiah:latest
        name: xhdfsiah
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "58c64e69-4277-44f7-8727-25b46d253fb5"
        - name: Vless_Path
          value: "/vldawqsfsdg"
        - name: Vmess_UUID
          value: "58c64e69-4277-44f7-8727-25b46d253fb5"
        - name: Vmess_Path
          value: "/vmlkjwreyrty"
        - name: Share_Path
          value: "/v2link"
